server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios
    username: root
    password: 93112619028
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: USUARIO-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enable:true
  metrics:
    export:
      prometheus:
        enable: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
