server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

    username: postgres
    password: 93112619028
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

