global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'USUARIO-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.18:8081' ]
        labels:
          application: 'Usuario Service Application'
  - job_name: 'HOTEL-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.18:8082' ]
        labels:
          application: 'Hotel Service Application'
  - job_name: 'CALIFICACION-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.18:8083' ]
        labels:
          application: 'Calificacion Service Application'