server:
  port: 8086

jwt:
  secret: Nicolas123Nicolas123Nicolas123Nicolas123
  exp: 3600000

spring:
  application:
    name: AUTH-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
